AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
  App:
    Type: String
    Description: Name of the app
  Stack:
    Type: String
    Description: Name of the stack
  Stage:
    Type: String
    Description: Name of the stage
    AllowedValues:
    - DEV
    - CODE
    - PROD
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
  DBInstanceType:
    Type: String
    Description: AWS instances type for the rds database
    Default: db.t2.micro
    AllowedValues:
    - db.t2.micro
  PostgresEngineVersion:
    Type: String
    Description: Version of postgres to use
  DBUsername:
    Type: String
    Description: Master username for the DB instance
  DBPassword:
    Type: String
    Description: Password for the DB instance
    NoEcho: true
  DBPort:
    Type: String
    Description: Port number for the database instance
    Default: 5432
  EditorialProductionMetricsInstanceSecurityGroup:
    Type: String
    Description: Security Group that should be given access to DEV DB
Resources:
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "DB security group servers"
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref DBPort
        ToPort: !Ref DBPort
        SourceSecurityGroupId: !Ref EditorialProductionMetricsInstanceSecurityGroup
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Private subnet for postgres database"
      SubnetIds: !Ref PrivateSubnets
  PostgresInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "5"
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: "1"
      DBInstanceClass: !Ref DBInstanceType
      DBInstanceIdentifier: !Sub ${App}-${Stage}
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBName: "metrics"
      Engine: "postgres"
      EngineVersion: !Ref PostgresEngineVersion
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      Port: !Ref DBPort
      Tags:
      - Key: Stage
        Value: !Ref Stage
      - Key: Stack
        Value: !Ref Stack
      VPCSecurityGroups:
      - !Ref DBSecurityGroup
