name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest

    permissions:
      # Allow GitHub to request an OIDC JWT ID token, for exchange with `aws-actions/configure-aws-credentials`
      # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#updating-your-github-actions-workflow
      id-token: write

      # Required for `actions/checkout`
      contents: read

    steps:
      # Seed the build number with last number from TeamCity.
      # This env var is used by the JS, and SBT builds, and guardian/actions-riff-raff.
      # Set the value early, rather than `buildNumberOffset` in guardian/actions-riff-raff, to ensure each usage has the same number.
      # For some reason, it's not possible to mutate GITHUB_RUN_NUMBER, so set BUILD_NUMBER instead.
      - name: Set BUILD_NUMBER environment variable
        run: |
          LAST_TEAMCITY_BUILD=790
          echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'yarn.lock'

      - name: JS Build
        run: |
          yarn install
          yarn build

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: 'sbt'

      - name: Scala Build
        run: |
          sbt clean compile testAll Debian/packageBin

      # Fetch AWS credentials, allowing us to upload to Riff-Raff (well, S3)
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      # Upload our build artifacts to Riff-Raff (well, S3)
      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: editorial-tools:editorial-production-metrics
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            editorial-production-metrics:
              - target/editorial-production-metrics_1.0_all.deb